from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import sys


class Ui_FSO_SENDER(object):
    def setupUi(self, FSO_SENDER):
        if not FSO_SENDER.objectName():
            FSO_SENDER.setObjectName(u"FSO_SENDER")
        FSO_SENDER.resize(630, 480)
        FSO_SENDER.setMinimumSize(QSize(620, 480))
        FSO_SENDER.setMaximumSize(QSize(630, 480))
        font = QFont()
        font.setFamily(u"Segoe Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        FSO_SENDER.setFont(font)
        FSO_SENDER.setAutoFillBackground(True)
        FSO_SENDER.setStyleSheet(u"")
        self.centralwidget = QWidget(FSO_SENDER)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(360, 110, 251, 261))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.circularProgressBar_Main = QFrame(self.verticalLayoutWidget)
        self.circularProgressBar_Main.setObjectName(u"circularProgressBar_Main")
        self.circularProgressBar_Main.setStyleSheet(u"background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QFrame.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QFrame.Raised)
        self.circularProgressCPU_2 = QFrame(self.circularProgressBar_Main)
        self.circularProgressCPU_2.setObjectName(u"circularProgressCPU_2")
        self.circularProgressCPU_2.setGeometry(QRect(10, 10, 220, 220))
        self.circularProgressCPU_2.setStyleSheet(u"QFrame{\n""	border-radius: 110px;	\n""	background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n""}")
        self.circularProgressCPU_2.setFrameShape(QFrame.StyledPanel)
        self.circularProgressCPU_2.setFrameShadow(QFrame.Raised)
        self.circularBg_2 = QFrame(self.circularProgressBar_Main)
        self.circularBg_2.setObjectName(u"circularBg_2")
        self.circularBg_2.setGeometry(QRect(10, 10, 220, 220))
        self.circularBg_2.setStyleSheet(u"QFrame{\n""	border-radius: 110px;	\n""	background-color: rgba(85, 85, 127, 100);\n""}")
        self.circularBg_2.setFrameShape(QFrame.StyledPanel)
        self.circularBg_2.setFrameShadow(QFrame.Raised)
        self.circularContainer_2 = QFrame(self.circularProgressBar_Main)
        self.circularContainer_2.setObjectName(u"circularContainer_2")
        self.circularContainer_2.setGeometry(QRect(25, 25, 190, 190))
        self.circularContainer_2.setBaseSize(QSize(0, 0))
        self.circularContainer_2.setStyleSheet(u"QFrame{\n""	border-radius: 95px;	\n""	background-color: rgb(58, 58, 102);\n""}")
        self.circularContainer_2.setFrameShape(QFrame.StyledPanel)
        self.circularContainer_2.setFrameShadow(QFrame.Raised)
        self.layoutWidget_2 = QWidget(self.circularContainer_2)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 40, 171, 125))
        self.infoLayout_2 = QGridLayout(self.layoutWidget_2)
        self.infoLayout_2.setObjectName(u"infoLayout_2")
        self.infoLayout_2.setContentsMargins(0, 0, 0, 0)
        self.labelAplicationName_2 = QLabel(self.layoutWidget_2)
        self.labelAplicationName_2.setObjectName(u"labelAplicationName_2")
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(10)
        self.labelAplicationName_2.setFont(font1)
        self.labelAplicationName_2.setStyleSheet(u"color: #FFFFFF; background-color: none;")
        self.labelAplicationName_2.setAlignment(Qt.AlignCenter)

        self.infoLayout_2.addWidget(self.labelAplicationName_2, 0, 0, 1, 1)

        self.labelPercentageCPU_2 = QLabel(self.layoutWidget_2)
        self.labelPercentageCPU_2.setObjectName(u"labelPercentageCPU_2")
        font2 = QFont()
        font2.setFamily(u"Roboto Thin")
        font2.setPointSize(30)
        self.labelPercentageCPU_2.setFont(font2)
        self.labelPercentageCPU_2.setStyleSheet(u"color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.labelPercentageCPU_2.setAlignment(Qt.AlignCenter)
        self.labelPercentageCPU_2.setIndent(-1)

        self.infoLayout_2.addWidget(self.labelPercentageCPU_2, 1, 0, 1, 1)

        self.labelCredits_2 = QLabel(self.layoutWidget_2)
        self.labelCredits_2.setObjectName(u"labelCredits_2")
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(8)
        self.labelCredits_2.setFont(font3)
        self.labelCredits_2.setStyleSheet(u"color: rgb(148, 148, 216); background-color: none;")
        self.labelCredits_2.setAlignment(Qt.AlignCenter)

        self.infoLayout_2.addWidget(self.labelCredits_2, 2, 0, 1, 1)


        self.verticalLayout.addWidget(self.circularProgressBar_Main)

        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 341, 42))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ComportSelector = QComboBox(self.horizontalLayoutWidget)
        self.ComportSelector.setObjectName(u"ComportSelector")
        self.ComportSelector.setMinimumSize(QSize(250, 35))

        self.horizontalLayout.addWidget(self.ComportSelector)

        self.ConnectButton = QPushButton(self.horizontalLayoutWidget)
        self.ConnectButton.setObjectName(u"ConnectButton")
        self.ConnectButton.setMinimumSize(QSize(0, 35))
        font4 = QFont()
        font4.setFamily(u"Consolas")
        font4.setPointSize(14)
        font4.setBold(True)
        font4.setItalic(True)
        font4.setWeight(75)
        self.ConnectButton.setFont(font4)
        self.ConnectButton.setStyleSheet(u"color:#F72585;")

        self.horizontalLayout.addWidget(self.ConnectButton)

        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 160, 321, 151))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.textEdit = QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit.setObjectName(u"textEdit")
        font5 = QFont()
        font5.setFamily(u"Terminal")
        font5.setPointSize(14)
        font5.setBold(True)
        font5.setWeight(75)
        self.textEdit.setFont(font5)

        self.verticalLayout_2.addWidget(self.textEdit)

        self.verticalLayoutWidget_3 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(90, 60, 161, 36))
        self.TtileBox = QVBoxLayout(self.verticalLayoutWidget_3)
        self.TtileBox.setObjectName(u"TtileBox")
        self.TtileBox.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(u"label")
        font6 = QFont()
        font6.setFamily(u"Segoe Script")
        font6.setPointSize(16)
        font6.setBold(True)
        font6.setWeight(75)
        self.label.setFont(font6)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setStyleSheet(u"color:#7209B7;")
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.TtileBox.addWidget(self.label)

        self.horizontalLayoutWidget_2 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(40, 120, 281, 32))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Text_Mode = QPushButton(self.horizontalLayoutWidget_2)
        self.Text_Mode.setObjectName(u"Text_Mode")
        self.Text_Mode.setMinimumSize(QSize(0, 30))
        self.Text_Mode.setFont(font)
        self.Text_Mode.setStyleSheet(u"color:#3A0CA3;")

        self.horizontalLayout_2.addWidget(self.Text_Mode)

        self.pushButton = QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMinimumSize(QSize(0, 30))
        self.pushButton.setFont(font6)
        self.pushButton.setStyleSheet(u"color:#3A0CA3;")

        self.horizontalLayout_2.addWidget(self.pushButton)

        self.Upload_Button = QPushButton(self.centralwidget)
        self.Upload_Button.setObjectName(u"Upload_Button")
        self.Upload_Button.setGeometry(QRect(110, 380, 136, 30))
        self.Upload_Button.setMinimumSize(QSize(0, 30))
        self.Upload_Button.setFont(font6)
        self.Upload_Button.setStyleSheet(u"color:#3A0CA3;")
        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(370, 60, 231, 36))
        self.TtileBox_2 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.TtileBox_2.setObjectName(u"TtileBox_2")
        self.TtileBox_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font6)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setStyleSheet(u"color:#7209B7;")
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.TtileBox_2.addWidget(self.label_2)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 90, 621, 0))
        self.line.setMinimumSize(QSize(0, 0))
        self.line.setMaximumSize(QSize(16777215, 0))
        self.line.setStyleSheet(u"color: green;\n""")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(330, 110, 20, 401))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 100, 611, 21))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.horizontalLayoutWidget_3 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 320, 321, 42))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.lineEdit = QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMinimumSize(QSize(0, 37))
        font7 = QFont()
        font7.setFamily(u"Segoe Script")
        font7.setPointSize(11)
        font7.setBold(False)
        font7.setWeight(50)
        self.lineEdit.setFont(font7)

        self.horizontalLayout_3.addWidget(self.lineEdit)

        self.pushButton_2 = QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setMinimumSize(QSize(0, 30))

        self.horizontalLayout_3.addWidget(self.pushButton_2)

        self.verticalLayoutWidget_5 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(370, 10, 160, 41))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.Status = QLabel(self.verticalLayoutWidget_5)
        self.Status.setObjectName(u"Status")
        self.Status.setFont(font)
        self.Status.setStyleSheet(u"color:#E63946;")

        self.verticalLayout_3.addWidget(self.Status)

        FSO_SENDER.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(FSO_SENDER)
        self.statusbar.setObjectName(u"statusbar")
        FSO_SENDER.setStatusBar(self.statusbar)

        self.retranslateUi(FSO_SENDER)

        QMetaObject.connectSlotsByName(FSO_SENDER)


        self.ConnecteCompin = False
        self.DisableOtherFuctions()
    # setupUi

    def DisableOtherFuctions(self):
        self.lineEdit.setDisabled(True)
        self.pushButton.setDisabled(True)
        self.pushButton_2.setDisabled(True)
        self.Upload_Button.setDisabled(True)
        self.Text_Mode.setDisabled(True)
        self.circularProgressBar_Main.hide()
        self.FileMode()
        
    def TextMode(self):
        pass

    def FileMode(self):
        self.verticalLayoutWidget_2.hide()
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 110, 321, 151))
        self.Upload_Button.setGeometry(QRect(110, 220, 136, 30))
    
    def UploadingMode(self):
        pass

    def retranslateUi(self, FSO_SENDER):
        FSO_SENDER.setWindowTitle(QCoreApplication.translate("FSO_SENDER", u"FSO_SENDER", None))
        self.labelAplicationName_2.setText(QCoreApplication.translate("FSO_SENDER", u"<strong>TRANSFER</strong> RATE", None))
        self.labelPercentageCPU_2.setText(QCoreApplication.translate("FSO_SENDER", u"<p align=\"center\"><span style=\" font-size:50pt;\">60</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p>", None))
        self.labelCredits_2.setText(QCoreApplication.translate("FSO_SENDER", u"<html><head/><body><p>Speed: <span style=\" color:#ffffff;\">40 Kb/s</span></p></body></html>", None))
        self.ConnectButton.setText(QCoreApplication.translate("FSO_SENDER", u"Connect", None))
        self.textEdit.setHtml(QCoreApplication.translate("FSO_SENDER", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n""<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n""p, li { white-space: pre-wrap; }\n""</style></head><body style=\" font-family:'Terminal','Segoe Script'; font-size:14pt; font-weight:600; font-style:normal;\">\n""<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
#if QT_CONFIG(accessibility)
        self.label.setAccessibleDescription(QCoreApplication.translate("FSO_SENDER", u"0", None))
#endif // QT_CONFIG(accessibility)
        self.label.setText(QCoreApplication.translate("FSO_SENDER", u"Input Section", None))
        self.Text_Mode.setText(QCoreApplication.translate("FSO_SENDER", u"Text Mode", None))
        self.pushButton.setText(QCoreApplication.translate("FSO_SENDER", u"File Mode", None))
        self.Upload_Button.setText(QCoreApplication.translate("FSO_SENDER", u"Upload", None))
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleDescription(QCoreApplication.translate("FSO_SENDER", u"0", None))
#endif // QT_CONFIG(accessibility)
        self.label_2.setText(QCoreApplication.translate("FSO_SENDER", u"Monitoring Section", None))
        self.lineEdit.setText(QCoreApplication.translate("FSO_SENDER", u"  Select A file. png or txt", None))
        self.pushButton_2.setText(QCoreApplication.translate("FSO_SENDER", u"Select", None))
        self.Status.setText(QCoreApplication.translate("FSO_SENDER", u"Not conected", None))
    # retranslateUi



if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_FSO_SENDER()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())